### ISSUE TITLE
Default functionality in lytics.config file for getting Lytics ID

### ISSUE THREAD

**Issue by jplwood** [JeffDarchuk/LyticsSitecoreConnector#4]
Docs say to update the config to define how to acquire Lytics ID:

> Modify this config file with your Lytics key and define how to acquire the Lytics ID
> - Usually found in a user's cookies
> - Customizable through adding a custom pipeline processor to expose the user's Lytics ID

Is there default behavior backed in to get this from user's cookies? If not, could this be the default that could be overridden? (also I just don't know a ton about pipelines so I'm not sure how to do this)

**Comment by JeffDarchuk** [comment]
Been a while since i've dug into this project, but it looks like it defaults to using the "ly_segs" cookie which should be populated by the lytics javascript embed.  Looking into the code there really isn't an easy way to configure how the segments are updated through pipelines.

**Comment by jplwood** [comment]
Thanks so much for the quick response!

**Comment by JeffDarchuk** [comment]
no problem, good luck!
