### ISSUE TITLE
Sitecore 9 compatibility

### ISSUE THREAD

**Issue by junichif** [JeffDarchuk/LyticsSitecoreConnector#5]
This was reported to me by one of our clients

> [TypeLoadException: Could not load type 'Sitecore.Data.Proxies.ProxyDisabler' from assembly 'Sitecore.Kernel, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'.]
> 
> LyticsSitecoreConnector.Pipeline.Initialize.InitializeLytics.AssessSitecoreState() +0
> 
> LyticsSitecoreConnector.Pipeline.Initialize.InitializeLytics.Process(PipelineArgs args) +172
> 
> (Object , Object ) +9
> 
> Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
> 
> Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +236
> 
> Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
> 
> Sitecore.Nexus.Web.HttpModule.Application_Start() +215
> 
> Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +1184
> 
> System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +581
> 
> System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
> 
> System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
> 
> System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369
> 
> [HttpException (0x80004005): Could not load type 'Sitecore.Data.Proxies.ProxyDisabler' from assembly 'Sitecore.Kernel, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'.]
> 
> System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
> 
> System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
> 
> System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0
> 
> It appears the ProxyDisabler was deprecated and removed from Sitecore 9. Third party libraries will need to be compiled against the Sitecore 9 kernel so Lytics will need to rebuild their connector.
> 
> https://briancaos.wordpress.com/2018/01/22/in-sitecore-9-the-proxydisabler-have-been-retired-completely/
> 
> https://sitecoreblog.marklowe.ch/2018/12/10-issues-you-might-run-into-when-upgrading-to-sitecore-9/

**Comment by JeffDarchuk** [comment]
I don't have a way to test this anymore, but i removed the proxydisabler and updated the .net framework needed to work in SC 9.  Give that a try, i released a version 1.1.0 nuget package

**Comment by junichif** [comment]
That seemed to do the trick. They reinstalled it, and seems to be working correctly now. 
Thanks for your help @JeffDarchuk
