### ISSUE TITLE
Kind not available

### ISSUE THREAD

**Issue by avjonespdx** [JeffDarchuk/LyticsSitecoreConnector#6]
Hey Jeff -- One of our customers' tech resources is connecting Sitecore to Lytics and encountered an issue with segments not being picked up by the connector and passed through. 

They believe this is due to a value not being present in the configuration (“kind”:”segment”, in fact “kind”:x is not present at all).

`if (segment.kind == "segment")

ret.Add(new SimpleLyticsSegment()`

Segments created using cURL, segment.kind is not an available field. Any remedy?

**Comment by JeffDarchuk** [comment]
If there's a bug in the code i would suggest that they make the update and test it in their environment, I don't have the ability to test changes as i don't have access to an environment using Lytics anymore.  Once they have it working they can submit a PR and i can update the nuget package.
